#ifndef CONFIG_H
#define CONFIG_H

#define AIRTRASH_MAGICWORD "lord"

const int AIRTRASH_WAIT_SIZE = 16;
const int AIRTRASH_BUFFER_SIZE = 4096;
const int AIRTRASH_PORT_LOW = 9000;
const int AIRTRASH_PORT_HIGH = 9005;
const int AIRTRASH_TIMEOUT_USEC = 550;
const int AIRTRASH_MAX_TRIES = 50;

#endif
